version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.11.1
    - 5.19.0
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
  - dependency-name: ts-loader
    versions:
    - 8.0.13
    - 8.0.14
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
  - dependency-name: "@types/react-redux"
    versions:
    - 7.1.15
  - dependency-name: node-notifier
    versions:
    - 8.0.1
